### ISSUE TITLE
0.5.2 crash

### ISSUE THREAD

**Issue by bpahern** [MD2Korg/mCerebrum-AutoSense#10]
I ran into a potential bug this morning. After updating to AutoSense version 0.5.2, I re-downloaded the STU00201566 config file. The first time I attempted to configure devices by tapping the AutoSense button in Application Settings, the app went to a black screen for several minutes, then finally showed a message "AutoSense isn't responding. do you want to close it?"

I closed all apps and tried again. Everything worked okay on the second attempt.

**Comment by twhnat** [comment]
Should be resolved in the latest release.
