### ISSUE TITLE
Service stops

### ISSUE THREAD

**Issue by twhnat** [MD2Korg/mCerebrum-AutoSense#4]
The autosense service stops receiving data at random and doesn't restart.  Additionally, the counter randomly resets on the service screen.

**Comment by ssamiei** [comment]
Noticed no AutoSense signals yesterday afternoon when trying to view them via Plotter, checked the AutoSense app and saw that it wasn't running. I tapped "start" to restart the service.

**Comment by twhnat** [comment]
Deployed fabric.io to monitor for crashes.  I still do not know why this is happening.

**Comment by twhnat** [comment]
Should be resolved in the latest release.
